import type { Product } from "@/types";

export const productArrow : Product[] = [
    {
        id: 1,
        name: "Producto 1",
        image: "https://via.placeholder.com/150",
        status: 'Activo',
        price: 100,
    },
    {
        id: 2,
        name: "Producto 2",
        image: "https://via.placeholder.com/150",
        status: 'Inactivo',
        price: 200,
    },
    {
        id: 3,
        name: "Producto 3",
        image: "https://via.placeholder.com/150",
        status: 'Activo',
        price: 300,
    },
    {
        id: 4,
        name: "Producto 4",
        image: "https://via.placeholder.com/150",
        status: 'Activo',
        price: 400,
    },
    {
        id: 5,
        name: "Producto 5",
        image: "https://via.placeholder.com/150",
        status: 'Activo',
        price: 500,
    },
    {
        id: 6,
        name: "Producto 6",
        image: "https://via.placeholder.com/150",
        status: 'Activo',
        price: 600,
    },
    {
        id: 7,
        name: "Producto 7",
        image: "https://via.placeholder.com/150",
        status: 'Activo',
        price: 700,
    },
    {
        id: 8,
        name: "Producto 8",
        image: "https://via.placeholder.com/150",
        status: 'Activo',
        price: 800,
    },
    {
        id: 9,
        name: "Producto 9",
        image: "https://via.placeholder.com/150",
        status: 'Activo',
        price: 900,
    },
    {
        id: 10,
        name: "Producto 10",
        image: "https://via.placeholder.com/150",
        status: 'Inactivo',
        price: 1000,
    },
    {
        id: 11,
        name: "Producto 11",
        image: "https://via.placeholder.com/150",
        status: 'Activo',
        price: 1100,
    },
    {
        id: 12,
        name: "Producto 12",
        image: "https://via.placeholder.com/150",
        status: 'Activo',
        price: 1200,
    },
    {
        id: 13,
        name: "Producto 13",
        image: "https://via.placeholder.com/150",
        status: 'Activo',
        price: 1300,
    },
    {
        id: 14,
        name: "Producto 14",
        image: "https://via.placeholder.com/150",
        status: 'Activo',
        price: 1400,
    },
    {
        id: 15,
        name: "Producto 15",
        image: "https://via.placeholder.com/150",
        status: 'Activo',
        price: 1500,
    },
    {
        id: 16,
        name: "Producto 16",
        image: "https://via.placeholder.com/150",
        status: 'Activo',
        price: 1600,
    },
    {
        id: 17,
        name: "Producto 17",
        image: "https://via.placeholder.com/150",
        status: 'Activo',
        price: 1700,
    },
    {
        id: 18,
        name: "Producto 18",
        image: "https://via.placeholder.com/150",
        status: 'Activo',
        price: 1800,
    },
    {
        id: 19,
        name: "Producto 19",
        image: "https://via.placeholder.com/150",
        status: 'Activo',
        price: 1900,
    },
    {
        id: 20,
        name: "Producto 20",
        image: "https://via.placeholder.com/150",
        status: 'Activo',
        price: 2000,
    },
]
